--- #YAML:1.0
name:                W3C-LinkChecker
version:             4.4
abstract:            W3C Link Checker
license:             ~
author:              
    - The W3C Link Checker Team <www-validator@w3.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           0
    Config::General:               2.06
    File::Spec:                    0
    HTML::Parser:                  3.2
    LWP:                           5.802
    Net::IP:                       0
    Term::ReadKey:                 2
    Test::More:                    0
    Time::HiRes:                   0
    URI:                           1.31
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
