--- #YAML:1.0
name:                W3C-LinkChecker
version:             4.4
abstract:            W3C Link Checker
license:             open_source
author:              
    - W3C QA-dev Team <public-qa-dev@w3.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           0
    CGI::Carp:                     0
    CGI::Cookie:                   0
    Config::General:               2.06
    File::Spec:                    0
    Getopt::Long:                  2.17
    HTML::Entities:                0
    HTML::Parser:                  3.2
    HTTP::Request:                 0
    HTTP::Response:                1.5
    Locale::Country:               0
    Locale::Language:              0
    LWP::RobotUA:                  1.19
    LWP::UserAgent:                0
    Net::hostent:                  0
    Net::IP:                       0
    perl5lib:                      0
    Socket:                        0
    Term::ReadKey:                 2
    Test::More:                    0
    Text::Wrap:                    0
    Time::HiRes:                   0
    URI:                           1.31
    URI::Escape:                   0
    URI::file:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
